#!/bin/bash

mkdir -p "$SOURCE/$(dirname $1)"
pushd "$SOURCE/$(dirname $1)"

domain=$(cut -d'/' -f1 <<<$1)
repoPath=$(cut -d'/' -f2- <<<$1)
cloneURL="git@$domain:$repoPath.git"
git clone $cloneURL
popd
